/*
 * This source file was generated by the Gradle 'init' task
 */
package net.tkbunny.brainfuckkt

import kotlin.test.Test
import kotlin.test.assertTrue

import net.tkbunny.brainfuckkt.BrainfuckKt;
import java.io.OutputStream

class BrainfuckKtTest {
  val bf = BrainfuckKt()

  @Test
  fun brainfuckTestHelloWorld() {
     val out: String = bf.runBf("""
++++++++[>+++++++++<-]>. H
<++++++[>+++++<-]>-. e
+++++++.. l (x2)
+++. o
<+++++++++++++++++[>----<-]>+. (comma)
<+++[>----<-]>. (space)
<+++++++++++[>+++++<-]>. W
<++++[>++++++<-]>. o
+++. r
------. l
--------. d
+<+++++++++++++++++[>----<-]>. !
    """)

    assertTrue(out == "Hello, World!", "Brainfuck test #1 expected output 'Hello, World!', but got " + out)
  }

  @Test
  fun brainfuckTestByteCounter() {
    val out: String = bf.runBf("""
,[.,]
    """, "Test string :3 (È)".trim().toByteArray(Charsets.ISO_8859_1).inputStream())
    
    assertTrue(out == "Test string :3 (È)", "Brainfuck test #2 expected output 'Test string :3 (È)', but got " + out)
  }
}

